= 99 Erlang Problems 

erl99problems is training repository designed for a quick dip into Erlang functional programming without pain.
Based on Ninety-Nine Lisp Problems which based on Prolog problem list by werner.hett@hti.bfh.ch.

erl99problems include sync - tool which will compile, reload your code and run unit tests every time once you save your changes.

To get start:

* Install Erlang (if you don't have).
* Open terminal
* git clone https://github.com/spylik/erl99problems
* cd erl99problems && make
* ./start.sh (and do not close terminal).
* Open src/erl99problems.erl in your favorite editor, read annotation and try to solve your first p02 problem (p01 solved already as example).

First time you should run eunit:test(erl99problems) manually (where you run start.sh), but after sync will take care tests and and run it every time once you save your changes. You can implement tests for your functions in test/erl99problems_tests.erl as well.

Each problem should be solved without calls to Erlang standart modules (lists:, gb_trees:, etc) and without calls to Erlang build-in-functions (BIF).

Some useful links which will helps you to solve problems:

http://erlang.org/doc/programming_examples/funs.html
http://erlang.org/doc/programming_examples/list_comprehensions.html
http://learnyousomeerlang.com/starting-out-for-real

Happy hacking.
